import type { Metadata } from "next";
import { Playfair_Display } from "next/font/google";
import "./globals.css";

const font = Playfair_Display({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <div className="bg-white overflow-x-hidden text-black">
          {children}
        </div>
      </body>
    </html>
  );
}
